### ISSUE TITLE
 duplicate attribute on development_dependencies

### ISSUE THREAD

**Issue by franciscoGPS** [jetrockets/shrine.cr#11]
Adding shrine as a dependency breaks when running shards install and it can not complete the dependency installation process

![image](https://user-images.githubusercontent.com/52421533/97243447-f9ab2c00-17bb-11eb-810d-f7dd5bea4c5e.png)

**Comment by FranCoFeliz** [comment]
Nevermind. Adding the version solves the issue for the installation
` shrine:
    github: jetrockets/shrine.cr
    version: ~> 0.6.0`
It's addressed here. https://github.com/jetrockets/shrine.cr/pull/10#issuecomment-653583190

**Comment by franciscoGPS** [comment]
Nevermind. Adding the version solves the issue for the installation
shrine: github: jetrockets/shrine.cr version: ~> 0.6.0
It's addressed [here](https://github.com/jetrockets/shrine.cr/pull/10#issuecomment-653583190).
