### ISSUE TITLE
Different method signature for open and upload

### ISSUE THREAD

**Issue by franciscoGPS** [jetrockets/shrine.cr#16]
First, thanks a lot for this awesome shard. It's been very helpful. 

Just a couple of things I found: 
The upload method implementation does not adds the move parameter as part of its parameter list. This breaks on compile time. 
![image](https://user-images.githubusercontent.com/6760672/107525766-c8911480-6b7c-11eb-88f5-1bc43ce9e97b.png)

![image](https://user-images.githubusercontent.com/6760672/107525594-9da6c080-6b7c-11eb-8807-44fbb9b668ca.png)

This is the way it should be.
![image](https://user-images.githubusercontent.com/6760672/107525561-92ec2b80-6b7c-11eb-8eb8-e9e612741bd6.png)

The same for the open method. The signature is not the same stated on the base abstract class:
Open method has an extra _**options_ params, that memory doesn't show and breaks on compile time:
![image](https://user-images.githubusercontent.com/6760672/107526107-1c036280-6b7d-11eb-81ae-29c1b56320cb.png)

![image](https://user-images.githubusercontent.com/6760672/107525984-ffffc100-6b7c-11eb-8786-121f21cc8640.png)

This also happens for the S3::upload method, the signature differs:
from the abstract class:
 _def upload(io : IO | UploadedFile, id : String, move = false, **upload_options)_
from the S3 implementation:
 _def upload(io : UploadedFile, id : String, move = false, **upload_options)_

Thanks in advance

**Comment by matthewmcgarvey** [comment]
@franciscoGPS I believe all these issues were fixed in v0.6.1, specifically https://github.com/jetrockets/shrine.cr/pull/15

**Comment by igor-alexandrov** [comment]
@franciscoGPS is this still relevant?

**Comment by franciscoGPS** [comment]
OH! Awesone guys. Sorry for the late response. I haven't deal with those methods recently, but the #15 realy shows the main fix I pointed above. 
Thanks for your effort.
