### ISSUE TITLE
Implement S3 storage

### ISSUE THREAD

**Issue by igor-alexandrov** [jetrockets/shrine.cr#2]
Implement `Shrine::Storage::S3` based on [https://github.com/shrinerb/shrine/blob/master/lib/shrine/storage/s3.rb](https://github.com/shrinerb/shrine/blob/master/lib/shrine/storage/s3.rb).

**Comment by watzon** [comment]
So it looks like this project isn't too old https://github.com/taylorfinnell/awscr-s3. Should work for the adapter.

**Comment by igor-alexandrov** [comment]
Cool, I will work on S3 adapter when `Shrine::Attacher` will be completed.

**Comment by igor-alexandrov** [comment]
Added with #3 
Released in 0.4.0! 🍺
