### ISSUE TITLE
Crystal 1.0 Support

### ISSUE THREAD

**Issue by matthewmcgarvey** [jetrockets/shrine.cr#22]
Seems like it might be a long road before Shrine is able to support Crystal 1.0 with a bunch of its dependencies still not there, but I thought I'd make an issue anyways. Hopefully we can get started hunting down and updating these libraries since this shard is crucial for a whole bunch of Lucky apps.

![](https://cdn.discordapp.com/attachments/743908611696361673/826545982309269574/CleanShot_2021-03-30_at_15.57.41.png)

**Comment by igor-alexandrov** [comment]
Don't worry dudes. FastImage is already upgraded to support 1.0. Shrine is also on the way.

**Comment by igor-alexandrov** [comment]
So now, we are only waiting for https://github.com/taylorfinnell/awscr-s3 to support 1.0.0 and we are done.

**Comment by igor-alexandrov** [comment]
So https://github.com/taylorfinnell/awscr-s3 depends from https://github.com/crystal-community/timecop.cr.

I opened PR in `timecop.cr` https://github.com/crystal-community/timecop.cr/pull/6, hope we will be able to merge everything fast.

**Comment by matthewmcgarvey** [comment]
Seems like Crystal 1.0 support was added, but the `shard.yml` seems to be setup to _only_ support Crystal 1.0.0 https://github.com/jetrockets/shrine.cr/blob/af8e4f53dc728375dcda5d1bdd63a42688c5624f/shard.yml#L10

I think it should be updated to `crystal: ">= 1.0.0"`

**Comment by igor-alexandrov** [comment]
@matthewmcgarvey sorry for such a big delay, better late than never.
Released 0.6.3: https://github.com/jetrockets/shrine.cr/releases/tag/v0.6.3.
